### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by HQGamerimkarton** [clauadv/dbd-cheat#12]
Hey, ive some questions about your Cheats and how to install them. I never used VSC ever before and can you give me a quick introdution in how to use your code with it?
Second question is, whats meant by "Kernel Driver"?
Third question: is this Cheat safe?

**Comment by killteamseller** [comment]
same

**Comment by killteamseller** [comment]
...

**Comment by clauadv** [comment]
everything you asked here you can find on google or any other cheating forum. the cheat is not detected as long as you are not using public injectors such as face injector

**Comment by killteamseller** [comment]
how to install?
