### ISSUE TITLE
Anti Cheat Bypass?

### ISSUE THREAD

**Issue by WeLoveGaming** [clauadv/dbd-cheat#3]
Does this have an anti cheat bypass?
Is there a chance of getting banned?

**Comment by WeLoveGaming** [comment]
Also can you post a built version of this cheat? I keep getting errors while building.

**Comment by WeLoveGaming** [comment]
Also, what do I do with the .dll?

**Comment by clauadv** [comment]
> Does this have an anti cheat bypass?
> 
no, u need ur own bypass

**Comment by WeLoveGaming** [comment]
> > Does this have an anti cheat bypass?
> 
> no, u need ur own bypass

Where do I get this? And you didnt say what Im supposed to do with the .dll

**Comment by clauadv** [comment]
> Where do I get this? And you didnt say what Im supposed to do with the .dll

bro this source is for developers only

**Comment by WeLoveGaming** [comment]
> bro this source is for developers only

Yep.
