### ISSUE TITLE
Exits at the start of the match

### ISSUE THREAD

**Issue by jiaop5** [clauadv/dbd-cheat#4]
The cheat crashes when entering the match, I load it after the start screen, I also tried in the match. Please help me :(. 
Configuration - x64 Release
Injector - https://github.com/ALEHACKsp/face-injector-v2-1

![image](https://user-images.githubusercontent.com/89840630/148031938-46ea7790-fdcc-4452-8c0e-bd74ac55b6af.png)

**Comment by clauadv** [comment]
i dont have an account to test.. so i dont really know, last dbd update was 17 days ago so it should be fine

**Comment by clauadv** [comment]
pushed a temporary fix
