### ISSUE TITLE
compile the tool

### ISSUE THREAD

**Issue by Sithic** [clauadv/dbd-cheat#5]
I need help understanding how to compile the tool or if you can do it for easier download. I forked it and plan to study a bit to keep this alive. Thanks for any help.

**Comment by Sithic** [comment]
Additionally, you said internal so I assume a .dll file so what injector did you use and what is the method for those trying to use it? 
PH2, Xenos, Extreme, or others?

**Comment by clauadv** [comment]
> Additionally, you said internal so I assume a .dll file so what injector did you use and what is the method for those trying to use it? PH2, Xenos, Extreme, or others?

yes, its a dll file. you can use "face injector v2" to inject this but you'll get banned in 10 minutes by eac.
