### ISSUE TITLE
Crash in inject

### ISSUE THREAD

**Issue by X3da1337** [clauadv/dbd-cheat#9]
i inject it and crash

**Comment by clauadv** [comment]
how am i supposed to know why are u crashing? check ur injector, driver etc

**Comment by X3da1337** [comment]
What injector are you using?

**Comment by X3da1337** [comment]
I use https://www.unknowncheats.me/forum/anti-cheat-bypass/486277-injector-eac-undetected.html

**Comment by X3da1337** [comment]
> how am i supposed to know why are u crashing? check ur injector, driver etc

I use https://www.unknowncheats.me/forum/anti-cheat-bypass/486277-injector-eac-undetected.html

**Comment by X3da1337** [comment]
Give your contact pls
